apiVersion: v1
kind: Service
metadata:
  name: flask-bookreviews-service
spec:
  type: LoadBalancer
  selector:
    app: flask-bookreviews
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
